// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6Djei1qapoEawNzHwNYrSrbmWMn4IEbY',
    appId: '1:128836319609:web:f737ef9ef10559f92d57a8',
    messagingSenderId: '128836319609',
    projectId: 'online-learning-app-e8b52',
    authDomain: 'online-learning-app-e8b52.firebaseapp.com',
    storageBucket: 'online-learning-app-e8b52.firebasestorage.app',
    measurementId: 'G-J6PZ0WLHWM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNKgLEuuxWAFDroURUJRiXv0HvVrJOBbY',
    appId: '1:128836319609:android:a9a30fa6f8049ea52d57a8',
    messagingSenderId: '128836319609',
    projectId: 'online-learning-app-e8b52',
    storageBucket: 'online-learning-app-e8b52.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB6Djei1qapoEawNzHwNYrSrbmWMn4IEbY',
    appId: '1:128836319609:web:b947951009a8a70b2d57a8',
    messagingSenderId: '128836319609',
    projectId: 'online-learning-app-e8b52',
    authDomain: 'online-learning-app-e8b52.firebaseapp.com',
    storageBucket: 'online-learning-app-e8b52.firebasestorage.app',
    measurementId: 'G-GC2F5RDTSK',
  );
}
